from enum import StrEnum

class RadioEvent(StrEnum):
    RX_ENABLED = "RX_ENABLED"
    TX_ENABLED = "TX_ENABLED"
    DISABLED = "DISABLED"

    PACKET_SEEN_START = "PACKET_SEEN_START"
    PACKET_SEEN_DONE = "PACKET_SEEN_DONE"
    
    PACKET_COLLISION = "PACKET_COLLISION"

    PACKET_SEND_START = "PACKET_SEND_START"
    PACKET_SENT_DONE = "PACKET_SENT_DONE"

    PACKET_RECEIVED = "PACKET_RECEIVED"
    PACKET_LOST = "PACKET_LOST"

